added config file check

diff --git a/goto b/goto
--- a/goto
+++ b/goto
@@ -12,6 +12,12 @@ TMP="/tmp/login${RANDOM}"
 
 read IP USER PASSWORD PORT < "${MACHINE_LIST}"
 
+if [[ ${?} -ne 0 || -z "${PORT}" ]]
+then
+    echo "${0}: ${MACHINE_LIST} does not exist or format error" >&2
+    exit 1
+fi
+
 cat << EOF > "${TMP}"
 set timeout 8
 spawn -noecho ssh ${USER}@${IP} -p${PORT} -o StrictHostKeyChecking=no "${CMD}"
